-- WC2018 Table DDL

-- Database setup: http://www.oracle.com/webfolder/technetwork/tutorials/obe/db/oow10/php_db/php_db.htm
-- execute dbms_connection_pool.start_pool();
-- execute dbms_connection_pool.restore_defaults(); 

CREATE TABLE GROUP_STAGE (
	ID NUMBER PRIMARY KEY,
	GROUP_NAME VARCHAR2(2) NOT NULL,
	STAGE VARCHAR2(30 CHAR) NOT NULL,
	WIKI VARCHAR2(100 CHAR)
);

CREATE TABLE TEAM (
	ID NUMBER PRIMARY KEY,
	TEAM_NAME VARCHAR2(60 CHAR) NOT NULL,
	GROUP_STAGE REFERENCES GROUP_STAGE NOT NULL,
	STILL_IN_COMPETITION CHAR NOT NULL,
	WIKI VARCHAR2(100 CHAR)
);

CREATE TABLE VENUE (
	ID NUMBER PRIMARY KEY,
	CITY VARCHAR2(60 CHAR) NOT NULL,
	STADIUM VARCHAR2(60 CHAR) NOT NULL,
	TIMEZONE VARCHAR2(5 CHAR),
	UTC_OFFSET NUMBER,
	IANA_TIMEZONE VARCHAR2(60 CHAR), -- (SELECT tzname, tzabbrev FROM V$TIMEZONE_NAMES;)
	WIKI_CITY VARCHAR2(100 CHAR),
	WIKI_STADIUM VARCHAR2(100 CHAR)
);

CREATE TABLE COUNTRY (
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(60 CHAR) NOT NULL,
	FLAG VARCHAR2(60 CHAR) NOT NULL
);

CREATE TABLE PLAYER (
	ID NUMBER PRIMARY KEY,
	TEAM REFERENCES TEAM NOT NULL,
	FIRST_NAME VARCHAR2(60 CHAR) NOT NULL,
	LAST_NAME VARCHAR2 (60 CHAR) NOT NULL,
	CLUB VARCHAR2(100 CHAR),
	WIKI VARCHAR2(100 CHAR),
	GOALS_SCORED NUMBER,
	YELLOW_CARDS NUMBER,
	RED_CARDS NUMBER,
	GOLDEN_BALL CHAR, -- (Best player)
	GOLDEN_BOOT CHAR, -- (Top goalscorer)
	GOLDEN_GLOVE CHAR, -- (Top Keeper)
	BEST_YOUNG_PLAYER CHAR
);

CREATE TABLE MANAGER (
	ID NUMBER PRIMARY KEY,
	TEAM REFERENCES TEAM NOT NULL,
	FIRST_NAME VARCHAR2(60 CHAR) NOT NULL,
	LAST_NAME VARCHAR2(60 CHAR) NOT NULL
);

CREATE TABLE COMPETITOR (
	ID NUMBER PRIMARY KEY,
	USERNAME VARCHAR2(60 CHAR) NOT NULL,
	PASSWORD VARCHAR2(60 CHAR) NOT NULL, -- (salted and hashed; see https://phpbestpractices.org/#passwords)
	FIRST_NAME VARCHAR2(60 CHAR) NOT NULL,
	LAST_NAME VARCHAR2(60 CHAR) NOT NULL,
	EMAIL VARCHAR2(60 CHAR), -- (see https://phpbestpractices.org/#validating-emails)
	COUNTRY REFERENCES COUNTRY NOT NULL,
	TEAM REFERENCES TEAM,
	ADMIN CHAR DEFAULT 'N' NOT NULL, 
	UPDATED_BY REFERENCES COMPETITOR,
	DATE_CREATED DATE NOT NULL, -- (server time)
	DATE_UPDATED DATE -- (server time)
);

CREATE TABLE MATCH (
	ID NUMBER PRIMARY KEY,
	KICKOFF_DATETIME DATE NOT NULL, -- (Timezones? SEE http://php.net/manual/en/function.date-default-timezone-set.php)
	BROADCASTER VARCHAR2(60 CHAR),
	VENUE REFERENCES VENUE NOT NULL,
	GROUP_STAGE REFERENCES GROUP_STAGE NOT NULL,
	TEAM_HOME REFERENCES TEAM,
	TEAM_AWAY REFERENCES TEAM,
	GOALS_HOME NUMBER,
	GOALS_AWAY NUMBER,
	ET_GOALS_HOME NUMBER,
	ET_GOALS_AWAY NUMBER,
	SHOOTOUT_GOALS_HOME NUMBER,
	SHOOTOUT_GOALS_AWAY NUMBER,
	PENS_AWARDED_HOME NUMBER, -- (PENS_* don't include Shoot-outs; triggers to update *_AWAY)
	PENS_AWARDED_AWAY NUMBER,
	PENS_SCORED_HOME NUMBER,
	PENS_SCORED_AWAY NUMBER,
	YELLOW_CARDS_HOME NUMBER, -- (triggers to update team table?)
	YELLOW_CARDS_AWAY NUMBER,
	RED_CARDS_HOME NUMBER,
	RED_CARDS_AWAY NUMBER
);

CREATE TABLE BET (
	ID NUMBER PRIMARY KEY,
	COMPETITOR REFERENCES COMPETITOR NOT NULL,
	MATCH REFERENCES MATCH NOT NULL,
	GOALS_HOME NUMBER NOT NULL,
	GOALS_AWAY NUMBER NOT NULL,
	VALID CHAR NOT NULL,
	POINTS NUMBER,
	DATE_CREATED DATE NOT NULL, -- (server time)
	DATE_UPDATED DATE -- (server time)
);

CREATE TABLE BONUS_COMPETITION (
	ID NUMBER PRIMARY KEY,
	COMPETITOR REFERENCES COMPETITOR NOT NULL,
	-- ?STILL_OPEN CHAR,
	WINNER REFERENCES TEAM,
	RUNNERS_UP REFERENCES TEAM,
	THIRD_PLACE REFERENCES TEAM,
	GOALS_SCORED NUMBER,
	YELLOW_CARDS NUMBER,
	RED_CARDS NUMBER,
	FAIR_PLAY_TROPHY REFERENCES TEAM, -- (Best disciplinary record)
	WORST_DISCIPLINE REFERENCES TEAM,
	MOST_ENTERTAINING_TEAM REFERENCES TEAM,
	GOLDEN_BALL REFERENCES PLAYER,
	GOLDEN_BOOT REFERENCES PLAYER,
	GOLDEN_GLOVE REFERENCES PLAYER,
	BEST_YOUNG_PLAYER REFERENCES PLAYER,
	ALL_STAR_MANAGER REFERENCES MANAGER,
	POINTS NUMBER,
	DATE_CREATED DATE NOT NULL, -- (server time)
	DATE_UPDATED DATE -- (server time)
);

-- WC2018 Sequence DDL

CREATE SEQUENCE SEQ_COMPETITOR_ID
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
	CACHE 20;

CREATE SEQUENCE SEQ_BET_ID
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
	CACHE 20;

CREATE SEQUENCE SEQ_BONUS_COMP_ID
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
	CACHE 20;

COMMIT;